# This GitHub workflow performs model deployment to production
# The workflow contents are largely the same as deploy-model-staging.yml but
# we split staging and prod model deployment into separate workflows to simplify
# separately tracking and viewing staging and prod model deployments via GitHub UI and API
#
# This workflow is triggered in an automated manner by the model training job (see notebooks/TriggerModelDeploy.py)
# after model training completes, to enable tracking and enforcing manual approval of model deployments in
# CD, if desired.
name: Prod Model Deployment for srijit_mlops_stack_demo

on:
  workflow_dispatch:
    inputs:
      modelUri:
        type: string
        description: 'URI of model to deploy, in the format models:/<model-name>/<version-id>'
        required: true

env:
  DATABRICKS_HOST: https://adb-8590162618558854.14.azuredatabricks.net
  DATABRICKS_TOKEN : ${{ secrets.DB_TOKEN }}
  NODE_TYPE_ID: Standard_D3_v2
  
jobs:
  prod:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Deploy model
        env:
          MLFLOW_TRACKING_URI: databricks
        run: |
          pip install mlflow
          python srijit_mlops_stack_demo/deployment/model_deployment/deploy.py "${{ github.event.inputs.modelUri }}" "prod"
